### ISSUE TITLE
How did you respond to input in the Jupyter Notebook

### ISSUE THREAD

**Issue by chidindu-ogbonna** [horizons-ml/OIDv4_annotation_tool#1]
I'm following your tutorial which led me to this code. 
I run the notebook, but the notebook can't respond to user input when the question comes up.

**Comment by horizons-ml** [comment]
Hi @chidindu-ogbonna , do you mean the inputs for the downloading the missing csv files?

**Comment by chidindu-ogbonna** [comment]
Yes, the input for downloading the files.

**Comment by horizons-ml** [comment]
Okay, did you try it on google colab? I just tried running the notebook again on google colab, and it runs fine taking the inputs generating the xml annotations as well

**Comment by chidindu-ogbonna** [comment]
I just tried it on google colab, and the program hangs when the input reaches. I have added a screencast of it.

https://user-images.githubusercontent.com/25098427/104086936-44393200-525c-11eb-9f28-f45b4569d055.mov

**Comment by horizons-ml** [comment]
I guess it is waiting for the user input. I'm attaching my screencast if it might help you

https://user-images.githubusercontent.com/73019877/104087190-eb7d8f80-5283-11eb-84da-9cb309f7d3c5.mp4

**Comment by chidindu-ogbonna** [comment]
OMG !!!

Thank you very much, I didn't know I could click on that 😂. I completely missed that.

Thank you very much for your time, really appreciate.

**Comment by horizons-ml** [comment]
I'm really glad that helped!!😃 Thanks for the feedback too.
